#!/usr/bin/env python3
from __future__ import annotations
from pathlib import Path
import json
import os

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "github-pages" / "vercel-env.generated.js"
RELEASE = "commission-v1.1-phaseN-remove-legacy-transport-2026-07-02-r1"
ASSET = "asset-manifest-commission-v1.1-phaseN-remove-legacy-transport-2026-07-02-r1"


def env_first(*names: str) -> str:
    for name in names:
        v = os.environ.get(name)
        if v is not None and str(v).strip() != "":
            return str(v).strip()
    return ""


def main() -> None:
    # Phase N intentionally does not publish GAS_WEB_APP_URL from server-only env.
    # Browser calls same-origin Vercel API endpoints only; legacy browser transports are removed.
    public_gas_fallback = env_first("NEXT_PUBLIC_GAS_WEB_APP_URL")
    cfg = {
        "phase": "N",
        # Keep deploy identity deterministic. Older Vercel env vars such as
        # NEXT_PUBLIC_APP_RELEASE_STAMP=phaseM-... can otherwise be written into
        # vercel-env.generated.js and trip the Phase N legacy-removal gate.
        "releaseStamp": RELEASE,
        "assetStamp": ASSET,
        "hostingTarget": "vercel-api-proxy",
        "vercelStaticFrontendReady": True,
        "vercelApiProxyEnabled": True,
        "phaseNLegacyTransportRemoved": True,
        "legacyJsonpTransportRemoved": True,
        "legacyGasBridgeTransportRemoved": True,
        "legacyLoginPostIframeRemoved": True,
        "vercelApiProxyUrl": env_first("NEXT_PUBLIC_VERCEL_API_PROXY_URL") or "/api/gas",
        "vercelLoginProxyUrl": env_first("NEXT_PUBLIC_VERCEL_LOGIN_PROXY_URL") or "/api/login",
        "vercelPublicConfigProxyUrl": env_first("NEXT_PUBLIC_VERCEL_PUBLIC_CONFIG_PROXY_URL") or "/api/public-config",
        "gasWebAppUrl": public_gas_fallback,
        "gasWebAppUrlPublicFallbackOnly": bool(public_gas_fallback),
        "gasWebAppUrlServerEnvRequired": True,
        "logoUrl": env_first("NEXT_PUBLIC_APP_LOGO_URL", "APP_LOGO_URL"),
        "vercelEnv": env_first("VERCEL_ENV"),
        "vercelUrl": env_first("VERCEL_URL"),
        "vercelProductionUrl": env_first("VERCEL_PROJECT_PRODUCTION_URL"),
        "gitCommitSha": env_first("VERCEL_GIT_COMMIT_SHA"),
        "generatedAt": env_first("SOURCE_DATE_EPOCH") or "build-time",
        "source": "tools/generate_vercel_env.py",
        "publicOnly": True,
    }
    js = (
        "//GENERATED by tools/generate_vercel_env.py.Public,non-secret values only.\n"
        "(function(root){'use strict';var cfg=" + json.dumps(cfg, ensure_ascii=False, separators=(",", ":")) + ";"
        "root.__VERCEL_MIGRATION_CONFIG__=Object.freeze(cfg);"
        "root.APP_DEPLOY_RELEASE=Object.assign({},root.APP_DEPLOY_RELEASE||{},"
        "{stamp:cfg.releaseStamp,assetStamp:cfg.assetStamp,hostingTarget:cfg.hostingTarget,"
        "phaseLVercelMigrationFoundation:true,phaseMVercelApiProxyEnabled:true,vercelApiProxyEnabled:true,phaseNLegacyTransportRemoved:true});"
        "})(window);\n"
    )
    OUT.write_text(js, encoding="utf-8")
    print(json.dumps({"ok": True, "output": str(OUT.relative_to(ROOT)), "release": cfg["releaseStamp"], "hasPublicGasFallbackUrl": bool(public_gas_fallback), "serverGasEnvRequired": True, "vercelApiProxyEnabled": True}, ensure_ascii=False))


if __name__ == "__main__":
    main()
