#!/usr/bin/env python3
from __future__ import annotations
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "github-pages" / "vercel-env.generated.js"
RELEASE = "commission-v1.2-hotfix-track-meeting-2026-07-09-r12"
ASSET = "asset-manifest-commission-v1.2-hotfix-track-meeting-2026-07-09-r12"
VERSION = "1.2.0-production-current"


def main() -> None:
    cfg = {
        "releaseTrack": "production-current",
        "version": VERSION,
        "releaseStamp": RELEASE,
        "assetStamp": ASSET,
        "hostingTarget": "vercel-api-proxy",
        "vercelStaticFrontendReady": True,
        "vercelApiProxyEnabled": True,
        "legacyTransportRemoved": True,
        "legacyJsonpTransportRemoved": True,
        "legacyGasBridgeTransportRemoved": True,
        "legacyLoginPostIframeRemoved": True,
        "vercelApiProxyUrl": "/api/gas",
        "vercelLoginProxyUrl": "/api/login",
        "vercelPublicConfigProxyUrl": "/api/public-config",
        "gasWebAppUrl": "",
        "gasWebAppUrlPublicFallbackOnly": False,
        "gasWebAppUrlServerEnvRequired": True,
        "logoUrl": "",
        "vercelEnv": "",
        "vercelUrl": "",
        "vercelProductionUrl": "",
        "gitCommitSha": "",
        "generatedAt": "build-time",
        "source": "tools/generate_vercel_env.py",
        "publicOnly": True,
        "deterministicPublicEnv": True,
    }
    js = (
        "//GENERATED by tools/generate_vercel_env.py.Public,non-secret deterministic values only.\n"
        "(function(root){'use strict';var cfg=" + json.dumps(cfg, ensure_ascii=False, separators=(",", ":")) + ";"
        "root.__VERCEL_MIGRATION_CONFIG__=Object.freeze(cfg);"
        "root.APP_DEPLOY_RELEASE=Object.assign({},root.APP_DEPLOY_RELEASE||{},"
        "{stamp:cfg.releaseStamp,assetStamp:cfg.assetStamp,version:cfg.version,hostingTarget:cfg.hostingTarget,"
        "vercelStaticFrontendReady:true,vercelApiProxyEnabled:true,legacyTransportRemoved:true});"
        "})(window);\n"
    )
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(js, encoding="utf-8")
    print(json.dumps({
        "ok": True,
        "output": str(OUT.relative_to(ROOT)),
        "release": cfg["releaseStamp"],
        "serverGasEnvRequired": True,
        "vercelApiProxyEnabled": True,
        "deterministicPublicEnv": True,
    }, ensure_ascii=False))


if __name__ == "__main__":
    main()
