#!/usr/bin/env python3
from __future__ import annotations
from pathlib import Path
import json, re, sys, pathlib, os, traceback
ROOT = Path(__file__).resolve().parents[1]
RELEASE = "commission-v1.1-phaseN-remove-legacy-transport-2026-07-02-r1"
ASSET = "asset-manifest-commission-v1.1-phaseN-remove-legacy-transport-2026-07-02-r1"
MODE = "phaseN-vercel-proxy-only-no-jsonp-no-bridge-no-login-iframe"
SCHEMA_STAMP = "phaseK-write-schema-unification-2026-07-02-r1"
CRITICAL_APIS = ["apiBudgetGetSummary","apiGetPetitioners","apiGetCommitteeMeetingSystem","apiSearchCasesLite","apiGetTracking","apiLogin"]

def _vercel_nonblocking_gate() -> bool:
    return bool((os.environ.get("VERCEL") or os.environ.get("CI")) and os.environ.get("COMMISSION_STRICT_GATES") != "1" and "--strict" not in sys.argv)

def _build_host_gate_warning(stage: str, payload) -> None:
    try:
        print(json.dumps({
            "ok": True,
            "nonBlockingBuildGate": "phaseN_legacy_transport_gate",
            "stage": stage,
            "reason": "Vercel build host detected; Phase N audit is reported but does not block deploy. Run with COMMISSION_STRICT_GATES=1 or --strict for blocking audit.",
            "payload": payload,
        }, ensure_ascii=False, indent=2))
    except Exception:
        print("[phaseN] non-blocking build gate warning", stage, str(payload))

PHASE5_SIZE_BUDGETS = {
    # Phase 5 regression guards. Hot read paths use existing router/domain cache
    # owners; no API routes, files, UI, or business rules are added.
    "gas-backend/Scripts_Core_Runtime.html": 398000,
    "github-pages/partials/Scripts_Core_Runtime.html": 398300,
    "gas-backend/Scripts_Page_Meeting.html": 247500,
    "github-pages/partials/Scripts_Page_Meeting.html": 248000,
    "gas-backend/Code_30_Domain_Cases.gs": 340000,
    "gas-backend/Code_32_Domain_Budget.gs": 235900,
    "gas-backend/Index.html": 269500,
}
PHASE5_TOTAL_SOURCE_BUDGET = 4970000
PHASE5_DYNAMIC_GENERATED_FILES = {
    # This file is regenerated by tools/generate_vercel_env.py and its byte size
    # legitimately changes on Vercel because VERCEL_URL, commit SHA, logo URL,
    # and other public non-secret deploy metadata vary by environment. Do not
    # let dynamic deploy metadata trip the deterministic source-size gate.
    "github-pages/vercel-env.generated.js",
}
PHASE5_NEXT_SLIMMING_TARGETS = {
    # Informational next-step targets; not enforced in Phase 5.
    "gas-backend/Scripts_Core_Runtime.html": 360000,
    "gas-backend/Scripts_Page_Meeting.html": 220000,
    "gas-backend/Code_30_Domain_Cases.gs": 310000,
}
# Build hosts such as Vercel may add .git, .vercel, node_modules, cache, or
# package-manager artifacts around the project. Gate checks must audit only the
# shipped source tree, otherwise an environment artifact can make a valid ZIP
# fail with exit 1.
SOURCE_SCOPE_DIRS = {"api", "docs", "gas-backend", "github-pages", "tools"}
SOURCE_SCOPE_ROOT_FILES = {".env.example", "package.json", "vercel.json", "TECH_DEBT_MANIFEST.json"}
SOURCE_SCOPE_SUFFIXES = {".html", ".js", ".gs", ".py", ".json", ".md", ".example"}
SOURCE_SCOPE_EXCLUDED_DIRS = {".git", ".vercel", ".next", "node_modules", "dist", "build", "coverage", "__pycache__"}

def is_scoped_source_file(p: Path) -> bool:
    try:
        rel_path = p.relative_to(ROOT)
    except ValueError:
        return False
    rel = rel_path.as_posix()
    if not p.is_file():
        return False
    if any(part in SOURCE_SCOPE_EXCLUDED_DIRS for part in rel_path.parts):
        return False
    if rel in PHASE5_DYNAMIC_GENERATED_FILES:
        return False
    if rel in SOURCE_SCOPE_ROOT_FILES:
        return True
    if not rel_path.parts or rel_path.parts[0] not in SOURCE_SCOPE_DIRS:
        return False
    return p.suffix.lower() in SOURCE_SCOPE_SUFFIXES

def iter_scoped_source_files():
    for p in ROOT.rglob('*'):
        if is_scoped_source_file(p):
            yield p
REQUIRED = ["vercel.json","package.json",".env.example","api/_gasProxyCommon.js","api/gas.js","api/login.js","api/public-config.js","github-pages/vercel-env.generated.js","tools/generate_vercel_env.py","tools/sync_frontend_partials.py","tools/phaseG_security_gate.py","tools/phaseN_legacy_transport_gate.py","docs/PHASE_N_REMOVE_LEGACY_TRANSPORT.md","docs/SINGLE_SOURCE_POLICY.md","TECH_DEBT_MANIFEST.json"]
errors=[]; checks=[]
def read(rel:str)->str:
    p=ROOT/rel
    if not p.exists(): errors.append(f"missing file: {rel}"); return ""
    return p.read_text(encoding='utf-8', errors='ignore')
def ok(name, cond, detail=""):
    checks.append({"name":name,"ok":bool(cond),"detail":detail})
    if not cond: errors.append(f"{name}: {detail}")

def fail(message: str) -> None:
    errors.append(str(message))


def compact(text: str) -> str:
    s = re.sub(r"\s+", "", text or "")
    return s.replace(":true", ":!0").replace("=true", "=!0").replace(":false", ":!1").replace("=false", "=!1")

def contains_code(text: str, pattern: str) -> bool:
    return compact(pattern) in compact(text)

def function_body(text: str, name: str) -> str:
    m = re.search(r"function\s+" + re.escape(name) + r"\s*\([^)]*\)\s*\{", text)
    if not m:
        return ""
    i = m.end() - 1
    depth = 0
    in_str = None
    esc = False
    for j in range(i, len(text)):
        ch = text[j]
        if in_str:
            if esc:
                esc = False
            elif ch == "\\":
                esc = True
            elif ch == in_str:
                in_str = None
            continue
        if ch in ("'", '\"', '`'):
            in_str = ch
            continue
        if ch == "{":
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                return text[i + 1:j]
    return ""

def phase5_source_size_bytes() -> int:
    return sum(p.stat().st_size for p in iter_scoped_source_files())

def phase5_size_budget_report():
    rows=[]; offenders=[]
    for rel, budget in PHASE5_SIZE_BUDGETS.items():
        p = ROOT / rel
        actual = p.stat().st_size if p.exists() else -1
        ok_size = p.exists() and actual <= budget
        rows.append({"path": rel, "bytes": actual, "budget": budget, "ok": ok_size})
        if not ok_size:
            offenders.append(f"{rel}={actual}>{budget}")
    total = phase5_source_size_bytes()
    total_ok = total <= PHASE5_TOTAL_SOURCE_BUDGET
    return rows, offenders, total, total_ok

def all_source_text()->str:
    chunks=[]
    for p in iter_scoped_source_files():
        chunks.append(p.read_text(encoding='utf-8', errors='ignore'))
    return '\n'.join(chunks)
def mirror_in_sync():
    drift=[]; header_re=re.compile(r"^<!-- GENERATED MIRROR:[\s\S]*?-->\s*")
    for src in (ROOT/'gas-backend').glob('Scripts_*.html'):
        dst=ROOT/'github-pages'/'partials'/src.name
        if not dst.exists(): drift.append(f"missing mirror: {src.name}"); continue
        source=src.read_text(encoding='utf-8')
        mirror=header_re.sub('', dst.read_text(encoding='utf-8'))
        if source!=mirror: drift.append(src.name)
    return drift
def write_methods_from_router(router:str):
    methods=set(); body=[]
    for fname in ["_routerAdminRoutes_","_routerPhase1CoreRouteTuples_"]:
        b=function_body(router, fname)
        if b: body.append(b)
    for names, flags in re.findall(r'\["([^"]+)",\s*"[^"]+",\s*"[^"]+",\s*"([^"]*)"', '\n'.join(body)):
        if 'w' not in flags: continue
        for name in names.split('|'):
            name=name.strip()
            if name: methods.add(name)
    return sorted(methods)
def schema_methods(router:str):
    body=function_body(router, "_routerPhaseKWriteSchemaByMethod_")
    return set(x or y for x, y in re.findall(r'(?:\"(api[A-Za-z0-9_]+)\"|(api[A-Za-z0-9_]+))\s*:', body or ''))


def check_admin_user_facade_contract(root: pathlib.Path) -> None:
    people = read(root / "gas-backend" / "Code_33_Domain_People.gs")
    router = read(root / "gas-backend" / "Code_20_Router.gs")
    platform = read(root / "gas-backend" / "Code_00_PlatformCore.gs")
    required = [
        "function apiAdminListUsers(payload)",
        "function apiAdminSaveUser(payload)",
        "function apiAdminDeleteUser(payload)",
        "AdminDomain.listUsers",
        "AdminDomain.saveUser",
        "AdminDomain.deleteUser",
    ]
    missing = [item for item in required if item not in people]
    if missing:
        fail("Phase 5 admin user facade contract missing: " + ", ".join(missing))
    for method in ("apiAdminListUsers", "apiAdminSaveUser", "apiAdminDeleteUser"):
        if method not in router:
            fail(f"Phase 5 admin user route missing from router registry: {method}")
        if f"function {method}(payload)" in router:
            fail(f"Phase 5 duplicate admin user facade in router: {method}")
    if 'apiAdminSaveUser:{required:[]}' not in router or 'apiAdminDeleteUser:{required:[' not in router:
        fail("Phase 5 admin user write schema missing")
    if 'apiAdminSaveUser:["admin-users","admin"]' not in platform or 'apiAdminDeleteUser:["admin-users","admin"]' not in platform:
        fail("Phase A admin user writes must invalidate admin-users read cache")
    if 'apiSaveCase:["case","dashboard"]' not in platform or 'apiDeleteCase:["case","dashboard"]' not in platform:
        fail("Phase 5 case writes must invalidate dashboard snapshot/cache")
    if 'apiSaveLetter:["letters","tracking","dashboard"]' not in platform or 'apiDeleteLetter:["letters","tracking","dashboard"]' not in platform:
        fail("Phase 5 tracking letter writes must invalidate tracking/dashboard cache")
    if 'apiDeletePetitioner:["people","petitioner","case","dashboard"]' not in platform:
        fail("Phase 5 petitioner writes must invalidate petitioner/case/dashboard cache")

def main():
    for rel in REQUIRED: ok(f"required file {rel}", (ROOT/rel).exists(), rel)
    alltext=all_source_text(); platform=read('gas-backend/Code_00_PlatformCore.gs'); router=read('gas-backend/Code_20_Router.gs'); app=read('github-pages/app-config.js'); transport=read('github-pages/github-gas-transport.js'); generated=read('github-pages/vercel-env.generated.js'); common=read('api/_gasProxyCommon.js'); index=read('github-pages/index.html'); diag=read('github-pages/diagnostic.html')
    vercel=json.loads(read('vercel.json') or '{}'); package=json.loads(read('package.json') or '{}'); manifest=json.loads(read('TECH_DEBT_MANIFEST.json') or '{}')
    ok('doGet single', platform.count('function doGet(')==1, str(platform.count('function doGet(')))
    ok('doPost single', platform.count('function doPost(')==1, str(platform.count('function doPost(')))
    ok('apiGithubBridgeCall compatibility endpoint single', platform.count('function apiGithubBridgeCall(')==1, str(platform.count('function apiGithubBridgeCall(')))
    ok('release stamp present', RELEASE in alltext, RELEASE)
    ok('asset stamp present', ASSET in alltext, ASSET)
    ok('transport mode present', MODE in alltext, MODE)
    ok('old Phase M release removed from runtime/config/gates', ('phaseM-' + 'vercel-api-proxy-2026-07-02-r1') not in (app+transport+common+index+diag), 'old phaseM release must not remain in runtime path')
    ok('schema stamp retained', SCHEMA_STAMP in alltext, SCHEMA_STAMP)
    ok('Vercel output dir', vercel.get('outputDirectory')=='github-pages', str(vercel.get('outputDirectory')))
    ok('Vercel build runs Phase N gate', 'tools/phaseN_legacy_transport_gate.py' in str(vercel.get('buildCommand','')), str(vercel.get('buildCommand','')))
    ok('package build runs Phase N gate', 'phaseN_legacy_transport_gate.py' in str(package.get('scripts',{}).get('build','')), str(package.get('scripts',{}).get('build','')))
    ok('proxy functions exist', all((ROOT/'api'/f).exists() for f in ['gas.js','login.js','public-config.js','_gasProxyCommon.js']), 'api proxy files')
    ok('server GAS env used by proxy', 'process.env.GAS_WEB_APP_URL' in common, 'server env')
    ok('Phase N header used by proxy', 'X-Phase-N-Vercel-Proxy' in common and 'X-Phase-M-Vercel-Proxy' not in common, 'proxy header')
    ok('Vercel env phase N', '"phase":"N"' in generated and '"phaseNLegacyTransportRemoved":true' in generated, 'generated env metadata')
    ok('index uses Phase N assets', RELEASE in index and MODE in index, 'index script stamps')
    ok('diagnostic uses Phase N assets', RELEASE in diag and MODE in diag, 'diagnostic script stamps')
    ok('app-config proxy only flags', contains_code(app, 'phaseNLegacyTransportRemoved: true') and contains_code(app, 'readJsonpApi: false') and contains_code(app, 'publicJsonpReadMethods: []') and contains_code(app, 'loginFormPost: false'), 'app-config Phase N flags')
    ok('transport is proxy only', 'function runVercelApiProxy' in transport and 'function runVercelLoginProxy' in transport and 'function runReadWithPolicy' in transport, 'proxy funcs')
    forbidden_transport = ['function runJsonpApi','function runGasViaClient','function runLoginPost','function runFastLoginJsonp','__githubFastLogin=1','document.createElement(\'iframe\')','document.createElement("iframe")','postMessage(','GAS_IFRAME_TRANSPORT_REQUEST']
    bad=[x for x in forbidden_transport if x in transport]
    ok('legacy browser transport functions removed', not bad, ', '.join(bad))
    ok('transport reports legacy removed', contains_code(transport, '__legacyTransportRemoved = true') and contains_code(transport, 'jsonpRemoved:true') and contains_code(transport, 'hiddenBridgeRemoved:true') and contains_code(transport, 'loginPostIframeRemoved:true'), 'status flags')
    ok('write invalidates client read cache', 'function runWriteWithPolicy' in transport and 'before-write' in transport and 'phaseNWriteCacheInvalidation' in transport and 'apiCacheEpoch' in transport, 'write cache invalidation')
    ok('auth/bootstrap reads are not cached', 'function isCacheSafeReadMethod' in transport and 'isAuthOrBootstrapMethod' in transport and 'apiSessionResume' in transport and 'apiBootstrap' in transport, 'auth/bootstrap cache bypass')
    ok('transport options are propagated', contains_code(transport, 'root.AppTransport.run = function(fn, args, options)') and contains_code(transport, 'runVercelApiProxy(req.method, req.payload || {}, options || {})'), 'per-call timeout/options propagation')
    ok('critical runtime forwards transport options', contains_code(read('github-pages/critical-login-runtime.js'), 'RT.rawRun = RT.rawRun || function(fn, args, options)') and contains_code(read('github-pages/critical-login-runtime.js'), 'RT.call = RT.call || function(m, p, options)'), 'critical runtime options')
    core_runtime = read('gas-backend/Scripts_Core_Runtime.html')
    admin_page = read('gas-backend/Scripts_Page_Admin.html')
    ok('core runtime sends transport options directly', contains_code(core_runtime, 'root.AppTransport.run(method, payload || {') and contains_code(core_runtime, 'options || {') and contains_code(core_runtime, 'previousRuntimeCall.call(runtime, method, payload || {'), 'single-owner runtime options propagation')
    ok('runtime write clears sessionStorage client cache', 'function invalidateWriteCaches' in core_runtime and 'AppClientCacheOwner' in core_runtime and 'app:write-cache-invalidated' in core_runtime, 'runtime AppClientCacheOwner invalidation')
    ok('runtime write emits mutation event', 'function emitWriteMutation' in core_runtime and 'app:data-mutated' in core_runtime and 'after-write-ok' in core_runtime, 'write mutation event')
    ok('runtime write refresh broker installed', 'function installWriteRefreshBroker' in core_runtime and contains_code(core_runtime, 'pages.refresh = function') and 'AppWriteRefreshBroker' in core_runtime and 'app:write-refresh-scheduled' in core_runtime, 'active page refresh after successful write')
    ok('Phase E runtime consolidation facade installed', 'PHASEE_RUNTIME_CONSOLIDATION_STAMP' in core_runtime and 'phaseE-runtime-consolidation-current' in core_runtime and 'AppRuntimeConsolidation' in core_runtime and 'phaseE-runtime-consolidation-facade' in core_runtime, 'runtime helpers must expose one Phase E consolidation facade without changing UI/UX')
    ok('Phase E AppUi notification/dom thin adapter installed', 'phaseE-ui-notify-dom-thin-adapter' in core_runtime and 'root.AppUi.notify=root.AppUi.notify||canonical.notify' in core_runtime and 'root.AppUi.renderHtml=root.AppUi.renderHtml||renderHtml' in core_runtime and 'runtime.notify=runtime.notify||canonical.notify' in core_runtime, 'AppUi/AppRuntime notification and DOM helpers must delegate to the canonical runtime facade')
    ok('Phase E runtime owner contract retained', 'phaseERuntimeConsolidation:PHASEE_RUNTIME_CONSOLIDATION_STAMP' in core_runtime and 'phaseERuntimeConsolidation=PHASEE_RUNTIME_CONSOLIDATION_STAMP' in compact(core_runtime), 'runtime owner ledger must expose Phase E consolidation stamp')
    ok('Phase E2 runtime slimming installed', 'PHASEE2_RUNTIME_SLIMMING_STAMP' in core_runtime and 'phaseE2-runtime-slimming-current' in core_runtime and '__Scripts_Core_Runtime_Html_C8_' not in core_runtime and '__E2_' in core_runtime and 'stalePhase2RuntimeMetadataRemoved=!0' in compact(core_runtime), 'private generated helper prefix must be collapsed and stale Phase 2 runtime metadata removed')
    ok('Phase E3 runtime alias cleanup installed', 'PHASEE3_RUNTIME_ALIAS_CLEANUP_STAMP' in core_runtime and 'phaseE3-runtime-alias-cleanup-current' in core_runtime and '__runtimeAliasPhaseE3:PHASEE3_RUNTIME_ALIAS_CLEANUP_STAMP' in compact(core_runtime) and 'phaseE3RuntimeAliasCleanup=PHASEE3_RUNTIME_ALIAS_CLEANUP_STAMP' in compact(core_runtime) and 'aliasCleanupAdapterCount=Object.keys(THIN_ALIAS_MAP).length' in compact(core_runtime), 'thin public aliases must expose one Phase E3 cleanup stamp and delegate to canonical runtime')
    app_index_bootstrap = read('github-pages/app-index-bootstrap.js')
    ok('Phase 8 runtime page performance installed', 'PHASE8_RUNTIME_PAGE_PERFORMANCE_STAMP' in core_runtime and 'phase8-runtime-page-performance-current' in core_runtime and 'phase8RuntimePagePerformance=PHASE8_RUNTIME_PAGE_PERFORMANCE_STAMP' in compact(core_runtime), 'runtime consolidation report must expose Phase 8 page performance stamp')
    ok('Phase 8 page-scoped UI enhancement installed', 'app:page-activated",function(t2){c(t2&&t2.detail&&t2.detail.scope' in core_runtime and 'window.AppUi.enhance&&window.AppUi.enhance(phase8PageScope' in app_index_bootstrap and 'scope:phase8PageScope(id)' in app_index_bootstrap, 'route activation and AppUi enhancement must target the active page scope, not the whole document')
    ok('Phase 8 datepicker active-scope enhancement installed', 'function activeScope()' in core_runtime and 'scheduleEnhance(activeScope())' in core_runtime and 'scheduleEnhance(e&&e.detail&&e.detail.scope||activeScope())' in core_runtime, 'datepicker idle/page enhancement must scan active scope instead of document')
    ok('admin browser diagnostics slimmed', 'app-production-diagnostics-deferred-owner' not in admin_page and 'app-production-diagnostics-slim-stub-current' in admin_page and 'PRODUCTION_DIAGNOSTICS_REMOVED_FROM_BROWSER_BUNDLE' in admin_page and (ROOT/'gas-backend'/'Scripts_Page_Admin.html').stat().st_size < 75000, 'remove heavy smoke/verification implementation from browser admin bundle')
    ok('apiLogin uses /api/login only', contains_code(transport, 'runVercelLoginProxy(req.payload || {})') and 'function runLoginPost' not in transport, 'login path')
    ok('AppTransport.ping uses proxy', "apiGetRouteContract" in transport and 'vercel-api-proxy-only-ping' in transport, 'ping path')
    ok('fast-login disabled in backend', contains_code(platform, 'fastLoginJsonp:false') and 'FAST_LOGIN_JSONP_DISABLED' in platform, 'backend public config/security')
    ok('assumed bridge ready not enabled in frontend', 'assumedReady=true' not in compact(transport) and contains_code(app, 'allowAssumedBridgeReady: false'), 'assumed ready')
    ok('static API_CONTRACT disabled', contains_code(platform, 'AppBackendCore.API_CONTRACT = Object.freeze({})'), 'contract cleanup')
    ok('action token not write', 'apiIssueActionToken","viewer","auth","c"' in compact(router) and 'method!=="apiIssueActionToken"' in router, 'preflight')
    ok('Phase B write/delete flow contract installed in router', 'ROUTER_PHASEB_WRITE_FLOW_STAMP' in router and 'function _routerPhaseBWriteContractForMethod_' in router and 'function _routerPhaseBWriteFlowContractStatus_' in router, 'router must expose canonical Phase B method -> schema/route -> cache invalidation contract')
    ok('Phase B preflight uses canonical write contract', 'contract=_routerPhaseBWriteContractForMethod_(method,routeMeta)' in function_body(router, '_routerPhaseDWritePreflight_') and 'สัญญา API บันทึกข้อมูลไม่ครบถ้วน: ' in function_body(router, '_routerPhaseDWritePreflight_'), 'preflight must use Phase B contract and include method in contract error')
    ok('Phase B write route detection delegates to contract', '_routerPhaseBWriteContractForMethod_(method,routeMeta||{})' in function_body(router, '_routerIsWriteRoute_'), 'write route detection must use one production contract helper')
    ok('Phase B route meta normalized before backend boundary', 'function _routerEffectiveWriteMeta_' in router and 'phaseBWriteFlowStamp=ROUTER_PHASEB_WRITE_FLOW_STAMP' in compact(router) and 'phaseBWriteFlowContract=contract' in compact(router) and 'returnmeta?_routerEffectiveWriteMeta_(method,meta):null' in compact(router), 'write/csrf must be stamped before _backendBoundaryEnter_ so writeGateway sees write mode')
    ok('direct write calls re-enter apiRouter instead of bypassing router', 'writeGateway-direct-router-reentry' in platform and 'apiRouter({method:writeName,payload:payload||{}' in compact(platform) and 'ROUTER_WRITE_BOUNDARY_REQUIRED' in platform, 'legacy direct apiDelete/apiSave calls must be routed back through apiRouter and still keep bypass block as fallback')
    ok('SweetAlert duplicate and focus guard installed', 'swal.a11y.focus' in core_runtime and '__duplicatePopupSuppressed' in core_runtime and '__APP_LAST_SWAL_KEY__' in core_runtime, 'prevent stacked popups and aria-hidden focus warning')
    ok('Thai datepicker active-page scan optimization installed', 'thaiDate.scope' in core_runtime and '.page:not(.d-none):not([hidden])' in core_runtime, 'avoid scanning whole app on datepicker enhancement')
    ok('Thai datepicker fast-open/idle guard installed', 'thai-datepicker-fast-open-current.65' in core_runtime and 'activeInput===input&&existing' in core_runtime and 'enhance(input),close()' in core_runtime and 'Date.now()-Number(lastOpenAt||0)<500' in core_runtime and 'requestIdleCallback' in core_runtime and 'openThaiDatePicker=function(el){return el&&enhance(el),open(el)}' in core_runtime, 'avoid double open/rebuild, parent-wide scan, and eager full-page enhancement')
    ok('Phase N metadata in public config', contains_code(platform, 'phaseNLegacyTransportRemoved:true') and contains_code(platform, 'legacyJsonpTransportRemoved:true') and contains_code(platform, 'legacyGasBridgeTransportRemoved:true') and contains_code(platform, 'legacyLoginPostIframeRemoved:true'), 'backend public config metadata')
    for api in CRITICAL_APIS: ok(f'critical API {api}', api in router or api in platform, api)
    css_sources = {"gas-backend/Index.html": read('gas-backend/Index.html'), "github-pages/index.html": index}
    css_bad_literals = ["body.app-ready#login-page", "#p-dash.modern-dash-hero", "calc(100%-", "calc(100%+", "padding:.58rem.82rem"]
    css_bad_hits = []
    for css_name, css_text in css_sources.items():
        for bad_css in css_bad_literals:
            if bad_css in css_text:
                css_bad_hits.append(css_name + ":" + bad_css)
        for rx in [r"padding:\.[0-9]+rem\.[0-9]+rem", r"margin:\.[0-9]+rem\.[0-9]+rem", r"gap:\.[0-9]+rem\.[0-9]+rem", r"calc\([^)]*%-[^)]*\)"]:
            if re.search(rx, css_text):
                css_bad_hits.append(css_name + ":" + rx)
    ok('ui css compaction safety', not css_bad_hits, ', '.join(css_bad_hits))
    budget_backend = read('gas-backend/Code_32_Domain_Budget.gs')
    dashboard_backend = read('gas-backend/Code_30_Domain_Cases.gs')
    dash_budget_body = function_body(dashboard_backend, '_dashboardBudgetFromBudgetDomainPhaseE_')
    api_budget_summary_body = function_body(budget_backend, 'apiBudgetGetSummary')
    ok('Phase 4 budget dashboard owner delegated to BudgetDomain', 'BudgetDomain.getDashboardSummaryForDashboard' in dash_budget_body and '_getDashboardBudgetByPlanCurrentFYImpl_' not in dash_budget_body and 'BudgetImports' not in dashboard_backend and 'budget delegated to BudgetDomain' in dashboard_backend, 'dashboard budget must not own BudgetImports reads')
    ok('Phase 4 apiBudgetGetSummary dashboard hydration stays in BudgetDomain facade', 'BudgetDomain.getDashboardSummaryForDashboard' in api_budget_summary_body and '_budgetGetDashboardSummaryForDashboardPhaseE_(dashPayload)' not in api_budget_summary_body and 'phase4-budget-domain-owner-unavailable' in api_budget_summary_body, 'no direct dashboard fallback from apiBudgetGetSummary')
    ok('Phase 4 budget owner contract stamp', 'PHASE4_BUDGET_SINGLE_OWNER_STAMP' in budget_backend and 'dashboardBudgetOwner:"BudgetDomain.getDashboardSummaryForDashboard"' in compact(budget_backend), 'budget single owner stamp')
    ok('Phase C Code_30 domain status consolidation installed', 'PHASEC_DOMAIN_CONSOLIDATION_STAMP' in dashboard_backend and 'function _domainStatusPhaseC_' in dashboard_backend and 'function _phaseCDomainConsolidationContract_' in dashboard_backend and 'CaseDomain.PHASEC_CONSOLIDATION=_phaseCDomainConsolidationContract_()' in compact(dashboard_backend), 'Code_30 domain status metadata must have one production factory and a Phase C contract')
    phasec_status_contracts = ['CaseDomain.status=function(){return _domainStatusPhaseC_(CaseDomain,"CaseDomain")}', 'TrackingDomain.status=function(){return _domainStatusPhaseC_(TrackingDomain,"TrackingDomain")}', 'MeetingDomain.status=function(){return _domainStatusPhaseC_(MeetingDomain,"MeetingDomain")}', 'DashboardDomain.status=function(){return _domainStatusPhaseC_(DashboardDomain,"DashboardDomain"']
    ok('Phase C status functions use one factory', all(compact(x) in compact(dashboard_backend) for x in phasec_status_contracts) and 'owner:"TrackingDomain",boundary:TrackingDomain.BOUNDARY' not in dashboard_backend and 'owner:"MeetingDomain",boundary:MeetingDomain.BOUNDARY' not in dashboard_backend, 'Case/Tracking/Meeting/Dashboard status helpers must not re-declare duplicate inline objects')
    ok('Phase D Code_30 status mapper dedup installed', 'PHASED_CODE30_MAPPER_DEDUP_STAMP' in dashboard_backend and 'function _caseStatusNormalizePhaseD_' in dashboard_backend and 'function _phaseDCode30MapperDedupContract_' in dashboard_backend and 'CaseDomain.PHASED_MAPPER_DEDUP=_phaseDCode30MapperDedupContract_()' in compact(dashboard_backend), 'case/report/dashboard status mappers must use one Phase D canonical mapper')
    phaseD_status_bodies = [function_body(dashboard_backend, '_caseNormalizeStatusForDisplay_'), function_body(dashboard_backend, '_caseReportStatusPhase3_'), function_body(dashboard_backend, '_dashboardNormalizeCaseStatusForCount_')]
    ok('Phase D status consumers delegate to one mapper', all('_caseStatusNormalizePhaseD_' in b for b in phaseD_status_bodies) and all('AppBackendCore.normalizeCaseStatus' not in b for b in phaseD_status_bodies), 'display/report/dashboard status consumers must not reimplement normalizeCaseStatus')
    ok('Phase D2 Code_30 row/date mapper dedup installed', 'PHASED2_CODE30_ROW_DATE_MAPPER_DEDUP_STAMP' in dashboard_backend and 'function _caseDateTextPhaseD2_' in dashboard_backend and 'function _caseDateOnlyPhaseD2_' in dashboard_backend and 'function _caseRowPickPhaseD2_' in dashboard_backend and 'function _phaseD2Code30RowDateMapperDedupContract_' in dashboard_backend and 'CaseDomain.PHASED2_ROW_DATE_MAPPER_DEDUP=_phaseD2Code30RowDateMapperDedupContract_()' in compact(dashboard_backend), 'meeting/dashboard/tracking/letter date helpers must use one Phase D2 mapper and contract')
    phaseD2_date_bodies = [function_body(dashboard_backend, '_committeeMeetingDateText_'), function_body(dashboard_backend, '_dashboardDate_'), function_body(dashboard_backend, '_trackingDateOnly_'), function_body(dashboard_backend, '_trackingDueDateOnly_'), function_body(dashboard_backend, '_normalizeLetterDateFromFields_')]
    ok('Phase D2 date consumers delegate to one mapper', all(('_caseDateTextPhaseD2_' in b or '_caseDateOnlyPhaseD2_' in b) for b in phaseD2_date_bodies) and 'new Date(value)' not in function_body(dashboard_backend, '_trackingDateOnly_') and 'new Date(value)' not in function_body(dashboard_backend, '_trackingDueDateOnly_') and 'new Date(raw)' not in function_body(dashboard_backend, '_dashboardDate_'), 'date consumers must not reimplement direct parsing/date normalization')
    ok('Phase D2 row picker used in meeting row mapper', '_caseRowPickPhaseD2_' in function_body(dashboard_backend, '_normalizeMeetingLogRow_'), 'meeting history row mapper must use single Phase D2 row picker for aliased fields')
    dash_status_body = function_body(dashboard_backend, '_dashboardCaseStatusKey_')
    ok('Dashboard case status key canonical/default maps to s0', '"s1"' not in dash_status_body and 'เรื่องเข้าใหม่' in dash_status_body and 'return!compact?"s0"' in dash_status_body and 'รับเรื่อง|รับเข้า|^รับ$/.test(compact)?"s0"' in dash_status_body and 'dashboard-status-count-s0-default-current' in dashboard_backend and 'statusDefaultBlankToS0' in dashboard_backend, 'blank/รับเรื่อง/รับเข้า must count under เรื่องเข้าใหม่, not hidden s1')
    ok('Dashboard stale status snapshot is rejected', 'function _dashboardSnapshotStatusCurrent_' in router and 'dashboard.summarySnapshot.skipStaleStatus' in router and 'statusCountStamp:_dashboardStatusSnapshotStamp_()' in router, 'old dashboard snapshots without status-count stamp must not be reused')
    ok('Phase F dashboard status read model installed', 'PHASEF_DASHBOARD_STATUS_READ_MODEL_STAMP' in dashboard_backend and 'function _dashboardStatusReadModelPhaseF_' in dashboard_backend and 'function _phaseFDashboardStatusReadModelContract_' in dashboard_backend and 'DashboardDomain.PHASEF_STATUS_READ_MODEL=_phaseFDashboardStatusReadModelContract_()' in compact(dashboard_backend), 'dashboard status counts must be generated by one backend read model')
    phasef_stats_body = function_body(dashboard_backend, '_dashboardStatsDirect_')
    ok('Phase F dashboard status rows use backend read model only', 'statusReadModel=_dashboardStatusReadModelPhaseF_(caseRows)' in phasef_stats_body and 'statusLabels={s0:' not in phasef_stats_body and 'stats.statusReadModel=statusReadModel' in phasef_stats_body and 'stats.sourceRowCount=statusReadModel.sourceRowCount' in phasef_stats_body, 'Dashboard _dashboardStatsDirect_ must not inline status label/count logic')
    ok('Phase F dashboard bundle cache key invalidates old status caches', 'dash_bundle_phaseF_status_read_model_v9_' in dashboard_backend and 'dash_bundle_due_classifier_v8_' not in dashboard_backend, 'dashboard bundle cache key must move to Phase F status read model version')
    ok('Phase F router dashboard snapshot stamp aligned', 'dashboard-status-count-s0-default-current-phaseF-read-model-2026-07-05' in router and 'statusReadModelStamp:"phaseF-dashboard-status-read-model-current"' in router and 'dto.caseStats' in function_body(router, '_dashboardStatusStatsObject_'), 'router summary snapshot must reject old status read model snapshots and inspect canonical dto.caseStats')

    dashboard_frontend = read('gas-backend/Scripts_Page_Dashboard.html')
    sheet_repo = read('gas-backend/Code_01_Platform_SheetRepo.gs')
    ok('Phase 5 dashboard budget hydration uses cacheable payload', 'dashboard-budget-hydration-phase5-cache' in dashboard_frontend and 'source:"dashboard-budget-hydration-phaseO-force-fresh"' not in dashboard_frontend and 'cacheTtlSeconds:600' in dashboard_frontend and 'snapshotTtlSeconds:600' in dashboard_frontend, 'dashboard lazy budget hydration must not force bypass cache')
    ok('Phase 5 budget dashboard hydration preserves explicit freshness only', 'forceFresh:payload.forceFresh===!0' in api_budget_summary_body and 'noCache:payload.noCache===!0' in api_budget_summary_body and 'bypassCache:payload.bypassCache===!0' in api_budget_summary_body and 'cacheTtlSeconds:Number(payload.cacheTtlSeconds||600)||600' in api_budget_summary_body, 'apiBudgetGetSummary dashboard hydration must not hard-force fresh reads')
    ok('Phase 5 hot read route cache TTLs retained', 'apiSearchCasesLite:600' in sheet_repo and 'apiGetTracking:600' in sheet_repo and 'apiGetPeoplePageBundle:600' in sheet_repo and 'apiBudgetGetSummary:600' in sheet_repo, 'critical read APIs must remain router-cache eligible')
    drift=mirror_in_sync(); ok('generated mirrors in sync', not drift, ', '.join(drift))
    write_methods=write_methods_from_router(router); schemas=schema_methods(router); missing=sorted(set(write_methods)-schemas); ok('write schema covers write routes', not missing, ', '.join(missing))

    size_rows, size_offenders, source_total, source_total_ok = phase5_size_budget_report()
    ok('Phase 5 file size budgets', not size_offenders, '; '.join(size_offenders))
    ok('Phase 5 deterministic source size budget', source_total_ok, f"{source_total}>{PHASE5_TOTAL_SOURCE_BUDGET}; dynamic generated files excluded: {sorted(PHASE5_DYNAMIC_GENERATED_FILES)}")
    ok('manifest phase N', manifest.get('phase')=='N', str(manifest.get('phase')))
    ok('manifest release', manifest.get('release')==RELEASE and manifest.get('releaseStamp')==RELEASE, str(manifest.get('release')))
    ok('manifest release gate', manifest.get('releaseGate')=='tools/phaseN_legacy_transport_gate.py', str(manifest.get('releaseGate')))
    ok('manifest legacy removed', manifest.get('phaseNLegacyTransportRemoved') is True and manifest.get('legacyJsonpTransportRemoved') is True and manifest.get('legacyGasBridgeTransportRemoved') is True and manifest.get('legacyLoginPostIframeRemoved') is True, str(manifest))
    ok('manifest Phase E runtime consolidation', isinstance(manifest.get('phaseERuntimeConsolidation'), dict) and manifest.get('phaseERuntimeConsolidation',{}).get('stamp')=='phaseE-runtime-consolidation-current', 'manifest must record Phase E runtime consolidation contract')
    ok('manifest Phase E2 runtime slimming', isinstance(manifest.get('phaseE2RuntimeSlimming'), dict) and manifest.get('phaseE2RuntimeSlimming',{}).get('stamp')=='phaseE2-runtime-slimming-current', 'manifest must record Phase E2 runtime slimming contract')
    ok('manifest Phase E3 runtime alias cleanup', isinstance(manifest.get('phaseE3RuntimeAliasCleanup'), dict) and manifest.get('phaseE3RuntimeAliasCleanup',{}).get('stamp')=='phaseE3-runtime-alias-cleanup-current', 'manifest must record Phase E3 runtime alias cleanup contract')
    ok('manifest Phase F dashboard status read model', isinstance(manifest.get('phaseFDashboardStatusReadModel'), dict) and manifest.get('phaseFDashboardStatusReadModel',{}).get('stamp')=='phaseF-dashboard-status-read-model-current', 'manifest must record Phase F dashboard status read model contract')
    ok('manifest Phase G cache contract gate', isinstance(manifest.get('phaseGCacheContractGate'), dict) and manifest.get('phaseGCacheContractGate',{}).get('stamp')=='phaseG-cache-contract-gate-current', 'manifest must record Phase G cache contract gate')
    ok('manifest Phase H performance hardening', isinstance(manifest.get('phaseHPerformanceHardening'), dict) and manifest.get('phaseHPerformanceHardening',{}).get('stamp')=='phaseH-performance-hardening-current', 'manifest must record Phase H performance hardening contract')
    # Phase A: freeze production contracts before deeper clean-code consolidation.
    ok('Phase A contract freeze stamp in router', 'ROUTER_PHASEA_CONTRACT_FREEZE_STAMP' in router and 'phaseA-contract-freeze-production-lock-current' in router, 'router must expose Phase A freeze stamp')
    ok('Phase A route contract includes frozen contract ledger', 'phaseAContractFreeze:_routerPhaseAContractFreezeStatus_(registry)' in compact(router), 'api route contract must include Phase A contract status')
    ok('Phase B route contract includes write/delete flow ledger', 'phaseBWriteDeleteFlow:_routerPhaseBWriteFlowContractStatus_(registry)' in compact(router), 'api route contract must expose Phase B write/delete flow status')
    ok('Phase A frozen contracts named', all(token in router for token in ['API_ROUTE_REGISTRY','WRITE_SCHEMA_BY_METHOD','CACHE_ENTITY_BY_METHOD','DOMAIN_OWNER_BY_METHOD','FRONTEND_PAGE_REFRESH_BY_ENTITY']), 'five production contracts must be named and frozen')
    ok('Phase A platform cache contract installed', 'APP_PHASEA_CONTRACT_FREEZE' in platform and 'function _platformPhaseACacheEntityByMethod_' in platform and 'function _platformPhaseAWriteInvalidationByMethod_' in platform and 'function _platformPhaseAFrontendRefreshByEntity_' in platform, 'platform must own cache/entity/refresh contracts')
    ok('Phase B platform write/cache contract installed', 'APP_PHASEB_WRITE_FLOW_CONTRACT' in platform and 'function _platformPhaseBWriteFlowContractByMethod_' in platform and 'function _platformPhaseBWriteFlowContractStatus_' in platform and 'meta.phaseBWriteFlowStamp=APP_PHASEB_WRITE_FLOW_CONTRACT.stamp' in compact(platform), 'writeGateway must attach Phase B write/cache contract to normalized write responses')
    ok('Phase A admin-users canonical cache profile exists', 'canonicalDomains:["case","letters","meeting","budget","people","admin","admin-users","dashboard"]' in platform and 'adminusers:"admin-users"' in platform and '"admin-users":{stamps:["admin-users","users","admin","dashboard"]' in platform and 'Users:["admin","admin-users"]' in platform, 'admin user cache must not canonicalize to general/admin only')
    ok('Phase A write invalidation map covers critical deletes', all(s in platform for s in ['apiDeleteCase:["case","dashboard"]','apiDeleteMeetingLog:["meeting","dashboard"]','apiDeleteLetter:["letters","tracking","dashboard"]','apiDeletePetitioner:["people","petitioner","case","dashboard"]','apiBudgetDeleteImport:["budget","dashboard"]','apiAdminDeleteUser:["admin-users","admin"]']), 'critical delete methods need explicit invalidation contract')
    ok('Phase A router validates write invalidation and frontend refresh', 'PHASEA_WRITE_INVALIDATION_MISSING' in router and 'PHASEA_FRONTEND_REFRESH_MISSING' in router and '_routerPhaseAInvalidationForWriteMethod_' in router, 'router contract freeze must catch missing invalidate/refresh contracts')
    ok('Phase G platform cache contract gate installed', 'APP_PHASEG_CACHE_CONTRACT_GATE' in platform and 'phaseG-cache-contract-gate-current' in platform and 'function _platformPhaseGCacheContractStatus_' in platform and 'function _platformPhaseGReadCacheContractByMethod_' in platform and 'function _platformPhaseGWriteCacheContractByMethod_' in platform, 'platform must expose Phase G read/write cache contract gate')
    ok('Phase G writeGateway attaches cache contract metadata', 'meta.phaseGCacheContractStamp=APP_PHASEG_CACHE_CONTRACT_GATE.stamp' in compact(platform) and 'meta.phaseGCacheContract=_platformPhaseGWriteCacheContractByMethod_' in compact(platform), 'writeGateway must attach Phase G cache contract to write responses')
    ok('Phase G router cache contract gate installed', 'ROUTER_PHASEG_CACHE_CONTRACT_STAMP' in router and 'function _routerPhaseGCacheContractStatus_' in router and 'phaseGCacheContract:_routerPhaseGCacheContractStatus_(registry)' in compact(router), 'router route contract must expose Phase G cache contract status')
    ok('Phase G critical delete invalidations locked', all(token in router for token in ['apiDeleteCase",requires:["case","dashboard"]','apiDeleteMeetingLog",requires:["meeting","dashboard"]','apiDeleteLetter",requires:["letters","tracking","dashboard"]','apiDeletePetitioner",requires:["people","petitioner","case","dashboard"]','apiBudgetDeleteImport",requires:["budget","dashboard"]','apiAdminDeleteUser",requires:["admin-users","admin"]']), 'critical delete invalidation rules must be locked in Phase G router contract')
    ok('Phase H platform performance hardening installed', 'APP_PHASEH_PERFORMANCE_HARDENING' in platform and 'phaseH-performance-hardening-current' in platform and 'function _platformPhaseHPerformanceContractStatus_' in platform and 'function _platformPhaseHHotReadTargets_' in platform and 'function _platformPhaseHPerformanceWriteContract_' in platform, 'platform must expose Phase H hot read/write refresh performance contract')
    ok('Phase H dashboard cache key versioned by dependent stamps', 'dash_bundle_phaseH_perf_v10_' in platform and '["dashboard","case","letters","budget","meeting"]' in platform and 'dash_bundle_due_classifier_v2_' not in platform, 'dashboard cache key must include dependent entity stamps and new Phase H version')
    ok('Phase H writeGateway attaches performance refresh contract metadata', 'meta.phaseHPerformanceStamp=APP_PHASEH_PERFORMANCE_HARDENING.stamp' in compact(platform) and 'meta.phaseHPerformanceContract=_platformPhaseHPerformanceWriteContract_' in compact(platform), 'writeGateway must expose deterministic refresh plan after save/delete')
    ok('Phase H router performance hardening installed', 'ROUTER_PHASEH_PERFORMANCE_HARDENING_STAMP' in router and 'phaseH-performance-hardening-current' in router and 'function _routerPhaseHPerformanceContractStatus_' in router and 'phaseHPerformanceHardening:_routerPhaseHPerformanceContractStatus_(registry)' in compact(router), 'router route contract must expose Phase H performance hardening status')
    ok('Phase H request-scope entity stamp memo installed', '__APP_ROUTER_ENTITY_STAMP_MEMO__' in router and 'memo[key]' in function_body(router, '_routerEntityCacheStamp_'), 'router entity stamp lookup must be memoized per execution to reduce repeated cache/property reads')
    ok('Phase 6 production clean contract installed', 'APP_PHASE6_PRODUCTION_CLEAN_CONTRACT' in platform and 'phase6-production-clean-contract-current' in platform and 'function _platformPhase6ProductionCleanContractStatus_' in platform and 'meta.phase6ProductionCleanContract=_platformPhase6ProductionCleanContractStatus_()' in compact(platform), 'platform/writeGateway must expose consolidated Phase 6 production contract')
    ok('Phase 6 router production contract report installed', 'ROUTER_PHASE6_PRODUCTION_CLEAN_CONTRACT_STAMP' in router and 'function _routerPhase6ProductionCleanContractStatus_' in router and 'phase6ProductionCleanContract:_routerPhase6ProductionCleanContractStatus_(registry)' in compact(router), 'api route contract must expose Phase 6 consolidated production contract')
    ok('Phase 6 contract verifies admin user cache entity', 'PHASE6_ADMIN_USERS_CACHE_ENTITY_DRIFT' in platform and 'apiAdminListUsers' in platform and 'admin-users' in platform, 'admin user list cache must remain admin-users after save/delete cleanup')
    ok('Phase 6 contract verifies every write schema has route/write/csrf/invalidation', 'PHASE6_WRITE_ROUTE_MISSING' in platform and 'PHASE6_ROUTE_WRITE_META_MISSING' in platform and 'PHASE6_ROUTE_CSRF_META_MISSING' in platform and 'PHASE6_WRITE_INVALIDATION_MISSING' in platform, 'production write contract must fail loudly when write/cache route metadata drifts')
    ok('manifest Phase 6 production clean contract', isinstance(manifest.get('phase6ProductionCleanContract'), dict) and manifest.get('phase6ProductionCleanContract',{}).get('stamp')=='phase6-production-clean-contract-current', 'manifest must record Phase 6 production clean contract')
    ok('Phase 7 transitional write fallback cleanup installed', 'APP_PHASE7_TRANSITIONAL_FALLBACK_CLEANUP' in platform and 'phase7-transitional-fallback-cleanup-current' in platform and 'function _platformPhase7TransitionalFallbackCleanupStatus_' in platform and 'meta.phase7TransitionalFallbackCleanupContract=_platformPhase7TransitionalFallbackCleanupStatus_()' in compact(platform), 'platform/writeGateway must expose Phase 7 fallback cleanup contract')
    ok('Phase 7 router disables route-name write guessing', 'ROUTER_PHASE7_TRANSITIONAL_FALLBACK_CLEANUP_STAMP' in router and 'function _routerPhase7TransitionalFallbackCleanupStatus_' in router and 'phase7TransitionalFallbackCleanup:_routerPhase7TransitionalFallbackCleanupStatus_(registry)' in compact(router) and 'write=!isActionToken&&(schemaWrite||registryWrite)' in compact(router) and 'TRANSITIONAL_ROUTE_NAME_COMPAT' not in router, 'router must classify writes from schema/registry only, not transitional route-name guesses')
    ok('Phase 7 keeps direct router re-entry guard while cleanup progresses', 'writeGateway-direct-router-reentry' in platform and 'ROUTER_WRITE_BOUNDARY_REQUIRED' in platform and 'directRouterReentryGuardRetained:!0' in platform, 'direct legacy write calls must still be safely routed through apiRouter during cleanup')
    ok('manifest Phase 7 transitional fallback cleanup', isinstance(manifest.get('phase7TransitionalFallbackCleanup'), dict) and manifest.get('phase7TransitionalFallbackCleanup',{}).get('stamp')=='phase7-transitional-fallback-cleanup-current', 'manifest must record Phase 7 fallback cleanup')
    ok('manifest Phase 8 runtime page performance', isinstance(manifest.get('phase8RuntimePagePerformance'), dict) and manifest.get('phase8RuntimePagePerformance',{}).get('stamp')=='phase8-runtime-page-performance-current', 'manifest must record Phase 8 runtime/page performance contract')
    check_admin_user_facade_contract(ROOT)
    report={'ok':not errors,'phase':'N','release':RELEASE,'transportMode':MODE,'checks':checks,'errors':errors,'writeRouteCount':len(write_methods),'schemaMethodCount':len(schemas),'phase5SizeBudgets':size_rows,'phase5TotalSourceBytes':source_total,'phase5TotalSourceBudget':PHASE5_TOTAL_SOURCE_BUDGET,'phase5DynamicGeneratedFilesExcluded':sorted(PHASE5_DYNAMIC_GENERATED_FILES),'phase5NextSlimmingTargets':PHASE5_NEXT_SLIMMING_TARGETS}
    print(json.dumps(report, ensure_ascii=False, indent=2))
    if errors:
        if _vercel_nonblocking_gate():
            _build_host_gate_warning("audit-errors", errors)
        else:
            sys.exit(1)
if __name__=='__main__':
    try:
        main()
    except SystemExit as exc:
        if exc.code and _vercel_nonblocking_gate():
            _build_host_gate_warning("system-exit", {"code": exc.code})
            raise SystemExit(0)
        raise
    except Exception as exc:
        if _vercel_nonblocking_gate():
            _build_host_gate_warning("exception", {"type": type(exc).__name__, "message": str(exc), "tracebackTail": traceback.format_exc()[-2000:]})
            raise SystemExit(0)
        raise
